spring:
  application:
    name: fxrate-service

server:
  port: 8302


eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://192.168.99.100:8761/eureka
  instance:
    hostname: http://192.168.99.100